
L_rb = doAnalyticalRB(sphere_radius, epsIn, epsOut, geometry.pqrData, ...
							 Nmax_RB);
L_trunc1 = doAnalytical(sphere_radius, epsIn, epsOut, geometry.pqrData, ...
							  1);
L_trunc2 = doAnalytical(sphere_radius, epsIn, epsOut, geometry.pqrData, ...
							  2);